version: "{build}"

image: Visual Studio 2017

configuration:
  - release
  - debug

clone_depth: 100
skip_tags: true
skip_commits:
  files:
    - .circleci/config.yml
    - .gitattributes
    - .gitignore
    - .gitmodules
    - .travis.yml
    - .travis_commands.bash
    - .travis_install.bash
    - .travis_script.bash
    - LICENSE
    - Makefile
    - release.bash
    - '**/*md'
    - '**/*.txt'

clone_folder: C:\projects\pony-appdirs
install:
  - ps: |
      $ErrorActionPreference = "Stop"
      cd C:\projects\pony-appdirs

      $package_commit = git rev-parse --short --verify "HEAD^{commit}"
      $package_iteration = "$package_iteration${env:appveyor_build_number}.$package_commit"
      if ($env:configuration -eq "debug")
      {
        $package_iteration = "$package_iteration-debug"
      }
      Update-AppveyorBuild -Version "pony-appdirs-$package_iteration"

      Write-Host "downloading ponyc..."
      $req = [System.Net.WebRequest]::Create("https://bintray.com/pony-language/ponyc-win/ponyc/_latestVersion")
      $req.AllowAutoRedirect = $false
      $req.Proxy = $null
      $req.Timeout = 500000
      $req.UserAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
      $res = $req.GetResponse()
      if ($res.StatusCode -eq "Found")
      {
        $latest_url = $res.GetResponseHeader("Location")
        $latest_ver = $latest_url.Substring($latest_url.LastIndexOf("/") + 1)
        $latest_ver = $latest_ver.Substring(0, $latest_ver.LastIndexOf("-"))
        
        $download_url = "https://bintray.com/pony-language/ponyc-win/download_file?file_path=" + $latest_ver + "-win64.zip"
        Write-Host "downloading pony from: " $download_url
        Invoke-WebRequest -Uri $download_url -OutFile ponyc.zip
        Expand-Archive "ponyc.zip" -DestinationPath "."
        Rename-Item ($latest_ver + "-win64") "ponyc"
      }
      else
      {
        Write-Host "Unable to determine latest Pony version from BinTray redirect!"
        exit 1
      }
      Write-Host "ponyc downloaded."
  - ps: |
      Write-Host "downloading pony-stable..."
      $req2 = [System.Net.WebRequest]::Create("https://bintray.com/pony-language/pony-stable-win/pony-stable/_latestVersion")
      $req2.AllowAutoRedirect = $false
      $req2.Proxy = $null
      $req2.Timeout = 500000
      $req2.UserAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::FireFox
      $res2 = $req2.GetResponse()
      if ($res2.StatusCode -eq "Found")
      {
        $latest_url2 = $res2.GetResponseHeader("Location")
        $latest_ver2 = $latest_url2.Substring($latest_url2.LastIndexOf("/") + 1)
        $download_url2 = "https://bintray.com/pony-language/pony-stable-win/download_file?file_path=" + $latest_ver2 + "-win64.zip"
        Write-Host "downloading pony-stable from: " $download_url2
        Invoke-WebRequest -Uri $download_url2 -OutFile pony-stable.zip
        Expand-Archive "pony-stable.zip" -DestinationPath "."
        Rename-Item ($latest_ver2 + "-win64") "pony-stable"
      }
      else
      {
        Write-Host "Unable to determine latest Pony-stable version from Bintray redirect!"
        exit 1
      }
      Write-Host "pony-stable downloaded."
  - ps: Write-Host "install done"

build_script:
    - echo "build script starting..."
    - cd C:\projects\pony-appdirs
    - set PATH=C:\projects\pony-appdirs\ponyc\ponyc\bin;C:\projects\pony-stable\release;%PATH%
    - make.bat config=%configuration%

test_script:
    - echo "test script starting..."
    - cd C:\projects\pony-appdirs
    - set PATH=C:\projects\pony-appdirs\ponyc\ponyc\bin;C:\projects\pony-stable\release;%PATH%
    - make.bat config=%configuration% test
deploy: off
