task:
  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

  osx_instance:
    image: mojave-xcode-11.2.1

  name: "PR: macOS"

  install_script:
    - brew install ponyc pony-stable

  test_script:
    - make test config=debug
