name: PR

on: pull_request

jobs:
  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  vs-ponyc-release:
    name: Test against recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug

  macOS:
    name: Test against recent ponyc release on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: brew install ponyc pony-stable
      - name: Test
        run: make test config=debug
